#cloud-config

apt:
  sources:
    mongodb.list:
      source: "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse"
      keyid: 9DA31620334BD75D9DCB49F368818C72E52529D4
    pritunl.list:
      source: "deb http://repo.pritunl.com/stable/apt xenial main"
      keyid: 7568D9BB55FF9E5287D586017AE645C0CF8E292A

package_update: true
package_upgrade: true

packages:
- docker.io
- jq
- awscli
- mongodb-org
- pritunl

runcmd:
- export AWS_DEFAULT_REGION=${aws_region}
- INSTANCE_ID=$(curl -Lfs http://169.254.169.254/latest/meta-data/instance-id)
- aws ec2 associate-address --instance-id $INSTANCE_ID --allocation-id ${eip}
- >
  echo '{
    "Comment": "auto updated @ '$(date)'",
    "Changes": [{
      "Action": "UPSERT",
      "ResourceRecordSet": {
        "Name": "'$(curl -Lfs http://169.254.169.254/latest/meta-data/local-hostname)'",
        "Type": "A",
        "TTL": 60,
        "ResourceRecords": [{
          "Value": "'$(curl -Lfs http://169.254.169.254/latest/meta-data/local-ipv4)'"
        }]
      }
    }]
  }' > /tmp/route53_update.json &&
  aws route53 change-resource-record-sets --hosted-zone-id ${dns_zone_id} --change-batch file:///tmp/route53_update.json
- mkdir -p /var/lib/mongodb
- aws ec2 attach-volume --instance-id $INSTANCE_ID --volume-id ${ebs} --device /dev/xvdx
- >
  while [ "$(aws ec2 describe-volumes --volume-ids ${ebs} | jq -r '.Volumes[].Attachments[] | select(.State == "attached") .InstanceId')" != "$INSTANCE_ID" ]; do
    sleep 10
  done
- mount /dev/xvdx /var/lib/mongodb && chown mongodb:mongodb /var/lib/mongodb
- systemctl enable pritunl mongod
- systemctl start pritunl mongod
- PRITUNL_KEY=$(pritunl setup-key)
- >
  nc -zv localhost 443
  while [ $? -ne 0 ]; do
    sleep 30
    nc -zv localhost 443
  done
  curl -Lkv -X PUT -H "content-type:application/json" -d '{"setup_key":"'"$PRITUNL_KEY"'","mongodb_uri":"mongodb://localhost:27017/pritunl"}' "https://vpn.${cluster_id}/setup/mongodb"
